#!/usr/bin/python2.7

import pycurl
from HTMLParser import HTMLParser
import sys

class PortParser(HTMLParser):
    __pastthead = False

    def handle_endtag(self, tag):
        if tag == "thead":
            self.__pastthead = True

    def handle_data(self, data):
        if (self.__pastthead):
            if self.get_starttag_text() == "<td>":
                if data.find("httpup") >= 0 or data.find("rsync") >= 0:
                    print data


if len(sys.argv) < 2 or sys.argv[1] == "-h":
    print "Usage: prt-search-db string"
    print "    This will search https://crux.nu/portdb for ports that match string and return a list of httpup and rsync locations."
    exit()

parser = PortParser()

url = "https://crux.nu/portdb/?a=search&q={0}".format(sys.argv[1])

c = pycurl.Curl()
c.setopt(c.URL, url)
c.setopt(c.WRITEFUNCTION, parser.feed)

parser.close()
c.perform()
