#!/bin/bash

if [[ "$1" == "-h" ]]; then
	echo "Sets the cpu governor on all cpu's"
	echo "Usage: $0 [governor]"
	echo "	Where governor is one of the avaliable governors in 'cpufreq-info -g'";
	exit
fi

if [[ `cpufreq-info -g` =~ $1 ]]; then
	ncpu=`cat /proc/cpuinfo | grep processor | wc -l`
	for i in `seq 1 $ncpu`; do cpufreq-set -c $(( $i - 1 )) -g $1; done
else
	echo "Governor '$1' not avaliable, try 'cpufreq-info -g' to list avaliable governors."
fi
